services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - '8080:8080'

  sms-sender:
    build:
      context: ./sms_sender
      dockerfile: Dockerfile
    environment:
      - 'TWILIO_ACCOUNT_SID=your_account_sid'
      - 'TWILIO_AUTH_TOKEN=your_auth_token'
    depends_on:
      - rabbitmq
      - api-gateway
    ports:
      - '8081:8080'

  email-sender:
    build:
      context: ./mail_sender
      dockerfile: Dockerfile
    environment:
      - 'SPRING_MAIL_HOST=localdomain.test'
      - 'SPRING_MAIL_PORT=587'
      - 'SPRING_MAIL_USERNAME=mail_sender'
      - 'SPRING_MAIL_PASSWORD=abracadabra12345'
      - 'SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true'
      - 'SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true'
    depends_on:
      - postgres
      - rabbitmq
      - api-gateway
    ports:
      - '8082:8080'